### ISSUE TITLE
PDF version of the CLA

### ISSUE THREAD

**Issue by f1k2faeez** [Comcast/.github#1]
Would like to contribute to Caption-Inspector for that would need the PDF version of the CLA

**Comment by kristakhare** [comment]
[ComcastContributorLicenseAgreement_03-07-14.pdf](https://github.com/Comcast/.github/files/3821455/ComcastContributorLicenseAgreement_03-07-14.pdf)
Hi @f1k2faeez thank you for your interest in contributing to one of our projects! Please see the PDF version attached. If you just wanted this for preview purposes and plan to sign via the CLA Assistant tool electronically, you'll be all set. Otherwise, please sign, scan and email to Comcast_Open_Source_Services@comcast.com
